<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>Contains Test Helpers mixin infrastructure. Shouldly is used for assertions.</Description>
    <LangVersion>11</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Core" Version="26.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
  </ItemGroup>
</Project>